version: '3'

services:
  mongodb:
    image: mongo:5.0.16
    container_name: mongodb
    restart: always
    ports:
      - 37017:27017
    environment:
      LC_ALL: 'C.UTF-8'
      TZ: 'Asia/Seoul'
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root-password
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./mongodb:/data/db
      - ./01-common.js:/docker-entrypoint-initdb.d/01-common.js:ro
    logging:
      options:
        max-size: '100k'

  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    restart: always
    ports:
      - 38801:8081
    environment:
      LC_ALL: 'C.UTF-8'
      TZ: 'Asia/Seoul'
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root-password
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
